import Head from 'next/head'
import { Inter } from '@next/font/google'
import { GetServerSideProps, NextPage } from 'next'
import { fetchCategories } from '../../http/index'
import { AxiosResponse } from 'axios'
import { ICategory, ICollectionResponces } from 'types'
import Tabs from '@/components/tabs/Tabs'

const inter = Inter({ subsets: ['latin'] })
interface IPropTypes {
  categories: {
    items: ICategory[]
  }
}

const Home: NextPage<IPropTypes> = (props: IPropTypes) => {
  const { categories } = props
  console.log(categories, "consolte")
  return (
    <>
      <Head>
        <title>Coder's Blog Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Tabs categories={categories.items} />
      <main >
        <div className='text-red-500'>
          body
        </div>
      </main>
    </>
  )
}
export default Home

export const getServerSideProps: GetServerSideProps = async () => {
  const { data: Categories }: AxiosResponse<ICollectionResponces<ICategory[]>> = await fetchCategories()
  return {
    props: {
      categories: {
        items: Categories.data
      }
    }
  }
}
